### ISSUE TITLE
Bad Links? https://hippie68.github.io/900/index.html

### ISSUE THREAD

**Issue by brandonnuner** [hippie68/hippie68.github.io#9]
I've been using your page (https://hippie68.github.io/900/index.html) for a long time along with the FTP server and scripts provided. Great tools! I've recently noticed the links on the bottom of the page are not working on my PS4. It could be me/my console. I don't have another one to test with. But after a couple weeks of it not working, I'd figured to message you. Thanks

**Comment by hippie68** [comment]
Thanks for reporting. I could reproduce the bug. It seems the current way of selecting links doesn't work properly anymore with offline caching. Meaning that it only works when there's an active network connection. I will try to fix it and report back.

**Comment by hippie68** [comment]
The links should work now, however: After updating the website, I have noticed that on my 9.00 PS4 cleaning the website cache (in the browser settings) did not properly erase the cache from memory. So the browser continued to use the old website version (even old payloads) until a reboot. This may be a 9.00 PS4 web browser bug. So if with this new website version the bug continues despite manually cleaning the website cache, please reboot once.

**Comment by brandonnuner** [comment]
All is working now.. much appreciated!
